ZFS Version

diff --git a/build-template b/build-template
--- a/build-template
+++ b/build-template
@@ -8,7 +8,7 @@ fail() {
 
 # Shortcuts
 CWD=`pwd`
-BUILD=${BTRFS_ROOT}/${BTRFS_BUILD}
+BUILD=${ZFS_ROOT}/${ZFS_BUILD}
 ROOTRW=${BUILD}/rootfs.rw
 VARRW=${BUILD}/var.rw
 OPTRW=${BUILD}/opt.rw
@@ -20,7 +20,7 @@ HOMERO=${BUILD}/home
 DELTAS=${BUILD}/deltas
 
 # Do a bit of sanity test
-[ ! -d ${BTRFS_ROOT} ] && fail 1 "The directory ${BTRFS_ROOT} does not exists!" 
+[ ! -d /${ZFS_ROOT} ] && fail 1 "The directory ${ZFS_ROOT} does not exists!" 
 
 [ -d ${BUILD} ] && fail 2 "The directory ${BUILD} already exists!" 
 
@@ -33,8 +33,8 @@ Creating subvolumes
 *******************
 BANNER
 
-sudo btrfs subvolume create ${BUILD} || fail 3 "Unable to create build directory ${BUILD}"
-sudo btrfs subvolume create ${ROOTRW} || fail 3 "Unable to create rootfs directory ${ROOTRW}"
+sudo zfs create ${BUILD} || fail 3 "Unable to create build directory ${BUILD}"
+sudo zfs create ${ROOTRW} || fail 3 "Unable to create rootfs directory ${ROOTRW}"
 
 # Bootstrap Debian/Ubuntu
 cat <<-BANNER
@@ -43,7 +43,7 @@ Running debootstrap
 *******************
 BANNER
 
-sudo debootstrap --include=${EXTRA} ${BASE} ${ROOTRW} ${REP}
+sudo debootstrap --include=${EXTRA} ${BASE} /${ROOTRW} ${REP}
 
 # Mount proc and sys
 cat <<-BANNER
@@ -52,8 +52,8 @@ Mounting proc/sys
 *****************
 BANNER
 
-sudo mount sysfs ${ROOTRW}/sys -t sysfs
-sudo mount proc ${ROOTRW}/proc -t proc
+sudo mount sysfs /${ROOTRW}/sys -t sysfs
+sudo mount proc /${ROOTRW}/proc -t proc
 
 # Update hostname
 cat <<-BANNER
@@ -62,7 +62,7 @@ Setting Hostname
 ****************
 BANNER
 
-cat <<-EOF | sudo chroot ${ROOTRW} bin/bash -c "cat >/etc/hostname"
+cat <<-EOF | sudo chroot /${ROOTRW} bin/bash -c "cat >/etc/hostname"
 ${NAME}
 EOF
 
@@ -73,7 +73,7 @@ Setting Subutai Template Version
 ********************************
 BANNER
 
-cat <<-EOF | sudo chroot ${ROOTRW} bin/bash -c "cat >/etc/subutai_template_version"
+cat <<-EOF | sudo chroot /${ROOTRW} bin/bash -c "cat >/etc/subutai_template_version"
 ${NAME}@${VERSION}
 EOF
 
@@ -84,7 +84,7 @@ Setting Network Interfaces
 **************************
 BANNER
 
-cat <<-EOF | sudo chroot ${ROOTRW} bin/bash -c "cat >/etc/network/interfaces"
+cat <<-EOF | sudo chroot /${ROOTRW} bin/bash -c "cat >/etc/network/interfaces"
 # Subutai Networking Default Configuration
 
 # Local
@@ -105,7 +105,7 @@ Setting Repos
 BANNER
 
 if [ -n "${REPOS}" ]; then
-    echo "${REPOS}" | sudo chroot ${ROOTRW} bin/bash -c "cat >/etc/apt/sources.list"
+    echo "${REPOS}" | sudo chroot /${ROOTRW} bin/bash -c "cat >/etc/apt/sources.list"
 fi
 
 # Run update
@@ -115,8 +115,8 @@ Updating
 ********
 BANNER
 
-sudo chroot ${ROOTRW} bin/bash -c "DEBIAN_FRONTEND=noninteractive apt-get -y update"
-sudo chroot ${ROOTRW} bin/bash -c "DEBIAN_FRONTEND=noninteractive apt-get -y upgrade"
+sudo chroot /${ROOTRW} bin/bash -c "DEBIAN_FRONTEND=noninteractive apt-get -y update"
+sudo chroot /${ROOTRW} bin/bash -c "DEBIAN_FRONTEND=noninteractive apt-get -y upgrade"
 
 # Optional extras
 cat <<-BANNER
@@ -124,7 +124,7 @@ cat <<-BANNER
 *****************
 Installing extras
 BANNER
-sudo chroot ${ROOTRW} bin/bash -c "DEBIAN_FRONTEND=noninteractive apt-get -y --allow-unauthenticated install ${PKGS}"
+sudo chroot /${ROOTRW} bin/bash -c "DEBIAN_FRONTEND=noninteractive apt-get -y --allow-unauthenticated install ${PKGS}"
 
 # Create package list
 cat <<-BANNER
@@ -133,8 +133,8 @@ Creating package list
 *********************
 BANNER
 
-sudo chroot ${ROOTRW} bin/bash -c "dpkg --get-selections > /packages"
-sudo mv ${ROOTRW}/packages $BUILD
+sudo chroot /${ROOTRW} bin/bash -c "dpkg --get-selections > /packages"
+sudo mv /${ROOTRW}/packages /$BUILD
 
 # Clean up 
 cat <<-BANNER
@@ -143,9 +143,9 @@ Cleaning up
 ***********
 BANNER
 
-sudo chroot ${ROOTRW} bin/bash -c "apt-get -y clean"
-sudo chroot ${ROOTRW} bin/bash -c "rm /var/cache/apt/*.bin"
-sudo chroot ${ROOTRW} bin/bash -c "rm -rf /var/lib/apt/lists/*"
+sudo chroot /${ROOTRW} bin/bash -c "apt-get -y clean"
+sudo chroot /${ROOTRW} bin/bash -c "rm /var/cache/apt/*.bin"
+sudo chroot /${ROOTRW} bin/bash -c "rm -rf /var/lib/apt/lists/*"
 
 # Unmount
 cat <<-BANNER
@@ -154,8 +154,8 @@ Unmounting temporary
 ********************
 BANNER
 
-sudo umount ${ROOTFS}/sys
-sudo umount ${ROOTFS}/proc
+sudo umount /${ROOTRW}/sys
+sudo umount /${ROOTRW}/proc
 
 # Deal with mounts
 cat <<-BANNER
@@ -164,14 +164,14 @@ Moving files
 ********************
 BANNER
 
-sudo btrfs subvolume create ${VARRW}
-sudo mv ${ROOTRW}/var/* ${VARRW}
+sudo zfs create ${VARRW}
+sudo mv /${ROOTRW}/var/* /${VARRW}
 
-sudo btrfs subvolume create ${OPTRW}
-sudo mv ${ROOTRW}/opt/* ${OPTRW}
+sudo zfs create ${OPTRW}
+sudo mv /${ROOTRW}/opt/* /${OPTRW}
 
-sudo btrfs subvolume create ${HOMERW}
-sudo mv $ROOTRW/home/* ${HOMERW}
+sudo zfs create ${HOMERW}
+sudo mv /$ROOTRW/home/* /${HOMERW}
 
 # Finally snapshot all
 cat <<-BANNER
@@ -180,10 +180,10 @@ Readonly snapshots
 ********************
 BANNER
 
-sudo btrfs subvolume snapshot -r ${ROOTRW} ${ROOTRO}
-sudo btrfs subvolume snapshot -r ${VARRW} ${VARRO}
-sudo btrfs subvolume snapshot -r ${OPTRW} ${OPTRO}
-sudo btrfs subvolume snapshot -r ${HOMERW} ${HOMERO}
+sudo zfs snapshot ${ROOTRW}@now
+sudo zfs snapshot ${VARRW}@now
+sudo zfs snapshot ${OPTRW}@now
+sudo zfs snapshot ${HOMERW}@now
 
 # Save deltas
 cat <<-BANNER
@@ -192,14 +192,14 @@ Creating deltas
 ********************
 BANNER
 
-sudo mkdir ${DELTAS}
-sudo btrfs send -f ${DELTAS}/rootfs.delta ${ROOTRO}
-sudo btrfs send -f ${DELTAS}/var.delta ${VARRO}
-sudo btrfs send -f ${DELTAS}/opt.delta ${OPTRO}
-sudo btrfs send -f ${DELTAS}/home.delta ${HOMERO}
+sudo mkdir /${DELTAS}
+sudo zfs send ${ROOTRW}@now | sudo tee /${DELTAS}/rootfs.delta >/dev/null
+sudo zfs send ${VARRW}@now | sudo tee /${DELTAS}/varfs.delta >/dev/null
+sudo zfs send ${OPTRW}@now | sudo tee /${DELTAS}/optfs.delta >/dev/null
+sudo zfs send ${HOMERW}@now | sudo tee /${DELTAS}/homefs.delta >/dev/null
 
 # Make sure deltas can be read by a normal user
-sudo chmod 644 $DELTAS/*
+sudo chmod 644 /${DELTAS}/*
 
 # Delete subvolumes
 cat <<-BANNER
@@ -208,14 +208,10 @@ Deleting subvolumes
 ********************
 BANNER
 
-sudo btrfs subvolume delete ${ROOTRW}
-sudo btrfs subvolume delete ${ROOTRO}
-sudo btrfs subvolume delete ${VARRW}
-sudo btrfs subvolume delete ${VARRO}
-sudo btrfs subvolume delete ${OPTRW}
-sudo btrfs subvolume delete ${OPTRO}
-sudo btrfs subvolume delete ${HOMERW}
-sudo btrfs subvolume delete ${HOMERO}
+sudo zfs destroy -r ${ROOTRW}
+sudo zfs destroy -r ${VARRW}
+sudo zfs destroy -r ${OPTRW}
+sudo zfs destroy -r ${HOMERW}
 
 # Create config
 cat <<-BANNER
@@ -224,7 +220,7 @@ Creating template config
 ************************
 BANNER
 
-cat <<-EOF | sudo tee ${BUILD}/config >/dev/null
+cat <<-EOF | sudo tee /${BUILD}/config >/dev/null
 # Subutai debian-stretch template
 lxc.arch = amd64
 # Network configuration
@@ -256,7 +252,7 @@ lxc.network.script.up = /snap/subutai-master/current/bin/create_ovs_interface
 
 EOF
 
-cat <<-EOF | sudo tee $BUILD/fstab
+cat <<-EOF | sudo tee /${BUILD}/fstab
 EOF
 
 # Bundle the darn thing in a tar.gz archive
@@ -267,7 +263,7 @@ Creating Bundle
 BANNER
 
 [ -d ${CWD}/build ] || mkdir ${CWD}/build
-(cd ${BUILD} ; tar cz * >${CWD}/build/${NAME}-subutai-template_${VERSION}_amd64.tar.gz)
+(cd /${BUILD} ; tar cz * >${CWD}/build/${NAME}-subutai-template_${VERSION}_amd64.tar.gz)
 
 # Finally nuke build
 cat <<-BANNER
@@ -276,7 +272,7 @@ Cleaning up
 ************************
 BANNER
 
-sudo btrfs subvolume delete ${BUILD}
+sudo zfs destroy -r ${BUILD}
 
 exit 0
 
